### ISSUE TITLE
calibre-web_(1) cloudn't be installed

### ISSUE THREAD

**Issue by zero617** [anderlli0053/AppArchive#1]
## Bug Report

![image](https://github.com/anderlli0053/AppArchive/assets/67105838/c2f0003d-119a-48ae-bebc-bad460ae3587)

**Comment by anderlli0053** [comment]
I screwed up while setting up this bucket. It was only meant for testing and archiving purposes and not as active bucket of any way.  Does the software that you try to install work in the DEV-Tools one? or any other one for that matter?

@zero617
